name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 187.124.163.90
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/defi-tracker-web
            git pull
            docker compose pull
            docker compose up -d
